version: '3'
services:

   cont:
      build: .
      image: pbx
      env_file:
         - .env
      volumes:
         - ./configs:/etc/configs
      restart: unless-stopped
      network_mode: host
