version: '3'
services:

   pbx:
      container_name: pbx
      #build: .
      image: genajan/pbx:latest
      env_file:
         - .env
      volumes:
         - ./configs:/etc/configs
      restart: unless-stopped
      network_mode: host
